3.0.0 UPDATE!
This update contain many bugfixes and improvements!

diff --git a/app/src/main/assets/93zipalign b/app/src/main/assets/93zipalign
--- a/app/src/main/assets/93zipalign
+++ b/app/src/main/assets/93zipalign
@@ -3,117 +3,47 @@
 busybox=/data/data/com.nowenui.systemtweakerfree/files/busybox
 
 #Zipalign /Data 
-RUN_EVERY=604800
 
 ZIPALIGNDB=/data/zipalign.db
-
-if [ -e $TD ]; then
-	rm $TD
-fi
 
 if [ ! -f $ZIPALIGNDB ]; then
 	touch $ZIPALIGNDB
 fi
 
-$busybox echo "" | tee -a $TD
-$busybox echo "" | tee -a $TD
-$busybox echo "Starting Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $TD
+$busybox echo "Starting Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )" 
 
-$busybox sleep 10
-
-for DIR in /data/app/*; do
-  cd $DIR
-  for APK in *.apk; do
-    if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ]; then
-      echo "Already checked: $DIR/$APK" | tee -a $TD
-    else
-       /system/xbin/zipalign -c 4 $APK
-      if [ $? -eq 0 ]; then
-        echo "Already aligned: $DIR/$APK" | tee -a $TD
-        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
-      else
-        echo "Now aligning: $DIR/$APK" | tee -a $TD
-        /system/xbin/zipalign -f 4 $APK /cache/$APK
-        $busybox mount -o rw,remount /system
-        cp -f -p /cache/$APK $APK
-		chmod 644 $APK
-        $busybox rm -f /cache/$APK
-        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
-      fi
-    fi
-  done
-done
-
-#Zipalign /system 
-
-for DIR in /system/app/*; do
-  cd $DIR
-  for APK in *.apk; do
-    if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ]; then
-      echo "Already checked: $DIR/$APK" | tee -a $TD
-    else
-      /system/xbin/zipalign -c 4 $APK
-      if [ $? -eq 0 ]; then
-        echo "Already aligned: $DIR/$APK" | tee -a $TD
-        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
-      else
-        echo "Now aligning: $DIR/$APK" | tee -a $TD
-        /system/xbin/zipalign -f 4 $APK /cache/$APK
-        $busybox mount -o rw,remount /system
-        cp -f -p /cache/$APK $APK
-		chmod 644 $APK
-        $busybox rm -f /cache/$APK
-        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
-      fi
-    fi
-  done
-done
-
-for DIR in /system/priv-app/*; do
-  cd $DIR
-  for APK in *.apk; do
-    if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ] ; then
-      echo "Already checked: $DIR/$APK" | tee -a $TD
-    else
-      /system/xbin/zipalign -c 4 $APK
-      if [ $? -eq 0 ]; then
-        echo "Already aligned: $DIR/$APK" | tee -a $TD
-        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
-      else
-        echo "Now aligning: $DIR/$APK" | tee -a $TD
-        /system/xbin/zipalign -f 4 $APK /cache/$APK
-        $busybox mount -o rw,remount /system
-        cp -f -p /cache/$APK $APK
-		chmod 644 $APK
-        $busybox rm -f /cache/$APK
-        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
-      fi
-    fi
-  done
-done
-
-for DIR in /system/framework; do
-  cd $DIR
-  for APK in *.apk ; do
-    if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ]; then
-      echo "Already checked: $DIR/$APK" | tee -a $TD
-    else
-      /system/xbin/zipalign -c 4 $APK
-      if [ $? -eq 0 ]; then
-        echo "Already aligned: $DIR/$APK" | tee -a $TD
-        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
-      else
-        echo "Now aligning: $DIR/$APK" | tee -a $TD
-        /system/xbin/zipalign -f 4 $APK /cache/$APK
-        $busybox mount -o rw,remount /system
-        cp -f -p /cache/$APK $APK
-		chmod 644 $APK
-        $busybox rm -f /cache/$APK
-        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
-      fi
-    fi
-  done
+for DIR in /data/app /system/app /system/priv-app
+do
+	cd $DIR;
+	for APK in *.apk */*.apk
+	do
+		if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ]; then
+			echo "Already checked: $DIR/$APK" 
+		else
+			ZIPCHECK=`/system/xbin/zipalign -c -v 4 $APK | grep FAILED | wc -l`
+			if [ $ZIPCHECK == "1" ]; then
+				echo "Now aligning: $DIR/$APK" 
+				/system/xbin/zipalign -f 4 $APK /data/local/$APK
+				rc = "$?"
+				if [ $rc -eq 0 ]; then
+					if [ -e "/data/local/$APK" ]; then
+						cp -f -p "/data/local/$APK" "$APK" 
+						rm -f "/data/local/$APK";
+						grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
+					else
+						echo "ZipAligning $APK Failed (no output file)"  
+					fi
+				else
+					[ -f "/data/local/$APK" ] && rm -f "/data/local/$APK"
+					echo "ZipAligning $APK Failed (rc: $rc)"  
+				fi
+			else
+				echo "Already aligned: $DIR/$APK" ;
+				grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
+			fi
+		fi
+	done
 done
 
 touch $ZIPALIGNDB
-$busybox echo "Automatic ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $TD
+$busybox echo "Automatic ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )" 
